name: sony
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  scoped_model: ^1.0.1
  get_it: ^3.0.3
  flutter_i18n: 0.8.0
  skeleton_text: 1.0.0
  date_format: ^1.0.8
  flutter_datetime_picker: 1.2.5
  shared_preferences: 0.5.3
  wc_form_validators: 0.1.1
  flushbar: 1.9.1

  openapi:
    path: ./openapi


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
    - family: FontAwesomeBrands
      fonts:
        - asset: assets/fonts/fa-brands-400.ttf
          weight: 400
    - family: FontAwesomeRegular
      fonts:
        - asset: assets/fonts/fa-regular-400.ttf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/fonts/fa-solid-900.ttf
          weight: 900
    - family: FontAwesomeDuotone
      fonts:
        - asset: assets/fonts/fa-duotone-900.ttf
          weight: 900
    - family: FontAwesomeLight
      fonts:
        - asset: assets/fonts/fa-light-300.ttf
          weight: 300

  assets:
    - assets/
    - assets/images/
    - assets/i18n/
